### ISSUE TITLE
Unable to run

### ISSUE THREAD

**Issue by PrakashMatkar** [yume-chan/turn-off-screen#1]
[screenoff-logcat.txt](https://github.com/yume-chan/turn-off-screen/files/14176764/screenoff-logcat.txt)
While I successfully built the project, running it resulted in a "Default activity not found" error. 
To address this, I made some changes to the AndroidManifest by adding the following:

`<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools">
    <application
        android:label="Test"
        android:supportsRtl="true">
        <activity
            android:name=".Main"
            android:exported="true">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
    </application>
</manifest>
`
However, after making these changes, build the project but I am unable to debug, and running the project is unsuccessful. Could you please suggest the correct way to test this on an emulator or a physical device?

**Comment by yume-chan** [comment]
This is not an Android app. Also, normal Android apps don't have the permission to call SurfaceComposer APIs.

See https://github.com/Genymobile/scrcpy/issues/3927#issuecomment-1790031953. Though, the code in this repository has been updated to remove LD_PRELOAD and system CLASSPATH requirements, so only `app_process -cp /data/local/tmp/test.jar / com.example.test.Main` is enough to use it.

**Comment by PrakashMatkar** [comment]
Thanks for the quick response, will be there any APIs or ways to implements and test the turn-off-screen feature for normal Android app. Please suggest if any

**Comment by yume-chan** [comment]
Normal apps can turn off the display and lock the device by injecting power button events using accessibility service, but I don't think it's possible to only turn off the display.

**Comment by PrakashMatkar** [comment]
we looked into the accessibility service. It's set to turn off the display and lock the device, but we only want it to turn off the display.
